### PR TITLE
feat: update renumber-test to new test schema

### PR DESCRIPTION
**Pull request by theseion**

### CODE REVIEW

**Review by fzipi — COMMENTED** [review]
So..... this is a breaking change, right?

If people have older versions of tests, they cannot use the new version of the tool 🤔 

Is that what we want?

**Comment by theseion** [comment]
That is correct, but they can use an older version of the tool. I could implement both if you think that's better.

**Comment by fzipi** [comment]
I'm not thinking about myself, it is just that there is other people out there that might use the tool and be puzzled about the need to downgrade.

**Comment by theseion** [comment]
Fair enough. I'll support both for now.

**Review by fzipi — APPROVED** [review]

**Pull request merged**
