### PR TITLE
Include except

### PR DESCRIPTION
**Pull request by theseion**
This PR introduces a new feature: the `include-except` processor. Similar to `include` processor, it reads contents of other files and adds them to the including file.

The `include-except` process take two arguments, an inclusion file, and an exclusion file. First, the inclusion file is treated as it would be for the `inclusion` processor. Then, all lines from the _exclusion_ file are **removed** from the inclusion file. The result of this operation is that the including file contains the contents of the inclusion file, as usual, but with some entries removed.

Entries must be identical to match.

### CODE REVIEW

**Comment by theseion** [comment]
@coreruleset/core-developers This is a proposal for a new processor. I would appreciate some feedback. An example of how it would be used:

```
some prefix

##!> include-except unix-shell unix-shell-dangerous

some suffix
```

The "exclusion files" will reside in a separate directory called `exclude` and will be allowed to contain only comments (`##!`)  or lines that match lines in an inclusion file.

**Comment by RedXanadu** [comment]
Two questions came to mind when reading the description of this new functionality.

1. It seems entirely possible for one to update an include file (remove a pattern, amend an anti-evasion technique, etc.) but forget to update all of the corresponding exclude files that may exist. Is there a way to ensure that _invalid_ excludes are flagged, which would force us to keep everything synchronised?

   E.g. if an exclude file is trying to exclude the pattern `abc` but I've already updated my include file which now contains the updated pattern `\babc\b`, could that cause an error and present a message to the user?

1. Is it possible to directly exclude a problematic entry? Like:

   `##!> include-except colours.list purple orange`

**Comment by theseion** [comment]
Thanks @RedXanadu.

> It seems entirely possible for one to update an include file (remove a pattern, amend an anti-evasion technique, etc.) but forget to update all of the corresponding exclude files that may exist. Is there a way to ensure that invalid excludes are flagged, which would force us to keep everything synchronised? Or would that just fail silently and not be caught? Or is that a linter task?
> 
> E.g. if an exclude file is trying to exclude the pattern abc but I've already updated my include file which now contains the updated pattern \babc\b, could that cause an error and present a message to the user?

Only matching lines matter. Superfluous entries in exclude files will be ignored. We could add a linter step at some point.

> Is it possible to directly exclude a problematic entry? Like:
> 
> ##!> include-except colours.list purple orange

No, currently not. I have thought about that and decided against it. There are two reasons for the decision:
1. While the length of a line is technically unlimited, reading the line becomes hard very quickly when the number of entries grows, especially when the line contains more complex entries (entries can be arbitrary regular expressions)
2. The alternative to 1. would be to represent the list of entries as individual lines, as it is done everywhere else. However, this doesn't work at the moment for a technical reason. The `include` and `include-except` steps actually happen at the parser stage, before the processors run and we don't have a way to go backwards in the parser stage. I could work around that limitation by introducing special internal processors but I try to avoid such hacks.

**Review by fzipi — APPROVED** [review]
LGTM. I was wondering if a flag to include would be better, but it doesn't change the result (e.g. `include <file> -except <file>`)

**Comment by theseion** [comment]
Yes, changing the syntax there would be very easy.

**Pull request merged**
